### ISSUE TITLE
Can't click on start after setting learning rate 

### ISSUE THREAD

**Issue by omah03** [omah03/Usable-Machine-Learning-#53]
<img width="981" alt="Screenshot 2024-02-02 at 21 33 46" src="https://github.com/omah03/Usable-Machine-Learning-/assets/96381116/bc1745f7-7d24-44e1-9a0e-ef08644ce003">

**Comment by BEATM-P** [comment]
I cant reproduce this, is it already fixed?

**Comment by q-uijote** [comment]
solved
